# Generated by Django 5.0.6 on 2026-06-16 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=8)),
                ('category', models.CharField(choices=[('workout_count', 'Workout Count'), ('streak', 'Streak'), ('volume', 'Volume'), ('exercises', 'Exercises'), ('nutrition', 'Nutrition'), ('goals', 'Goals')], max_length=30)),
                ('threshold', models.PositiveIntegerField(help_text='Value to reach (workouts, streak days, etc.)')),
                ('badge_color', models.CharField(default='emerald', max_length=20)),
            ],
            options={
                'ordering': ['category', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
