# Generated by Django 5.0.6 on 2026-06-16 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_calories_per_set_exercise_default_reps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('cardio', 'Cardio')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='goal',
            field=models.CharField(choices=[('general', 'General'), ('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('endurance', 'Endurance'), ('mobility', 'Mobility'), ('flexibility', 'Flexibility'), ('weight_loss', 'Weight Loss')], db_index=True, default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercisecompletion',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='exercisecompletion',
            index=models.Index(fields=['user', 'date'], name='exercises_e_user_id_8ecf41_idx'),
        ),
    ]
